# extension fieldsを使ってDRYに書く
# https://inokara.hateblo.jp/entry/2020/01/28/072937
x-image: &image
  image: ansible-target
  build:
    context: .
    args:
      - PUBLIC_KEY_PATH=${PUBLIC_KEY_PATH}

services:
  server1:
    <<: *image
    container_name: ansilbe-target1
    ports:
      - "8080:22"
  server2:
    <<: *image
    container_name: ansible-target2
    ports:
      - "8081:22"
